### ISSUE TITLE
Оптимизировать шрифты (?)

### ISSUE THREAD

**Issue by OlyErofeeva** [sudo-mode/turbina#131]
Пробовала добавить в стили .page вот это: 
```
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  -webkit-text-size-adjust: 100%;
  -ms-text-size-adjust: 100%;
  -moz-text-size-adjust: 100%;
```

но эфффекта не заметила

**Comment by OctopussyO** [comment]
Честно говоря, я разницы тоже не вижу. Но помню, как ребятам на челендже для "Шалаша" выкатили замечание про отсутствие сглаженных шрифтов.

**Comment by OctopussyO** [comment]
После оптимизации шрифты стали соответствовать макету (Pixel Perfect)
