### ISSUE TITLE
Неудобно читать текст песни на смартфонах

### ISSUE THREAD

**Issue by OlyErofeeva** [sudo-mode/turbina#157]
Сейчас в контейнере с текстом песни строки не переносятся, если не умещаются, а ставится многоточие. Нужно по возможности оставить многоточие для релизов, а для текста песни сделать перенос на новую строку..

**Comment by OctopussyO** [comment]
![image](https://user-images.githubusercontent.com/43892676/99156772-ba923b80-26d4-11eb-9e4a-51e64c60fe7e.png)

**Comment by SergeyMMedvedev** [comment]
![image](https://user-images.githubusercontent.com/65297595/99157326-de578080-26d8-11eb-8d6d-56cf951d7952.png)
сделал перенос

**Comment by SergeyMMedvedev** [comment]
https://github.com/sudo-mode/turbina/pull/163
