### ISSUE TITLE
Образается последняя буква в названии трека при наведении на трек

### ISSUE THREAD

**Issue by OctopussyO** [sudo-mode/turbina#158]
![image](https://user-images.githubusercontent.com/43892676/99156718-45266b00-26d4-11eb-95a9-c9c7cc294c3a.png)

**Comment by SergeyMMedvedev** [comment]
![image](https://user-images.githubusercontent.com/65297595/99157261-5ffade80-26d8-11eb-920d-88aac601b036.png)
исправлено

**Comment by SergeyMMedvedev** [comment]
https://github.com/sudo-mode/turbina/pull/163
