### ISSUE TITLE
На мобильных - не очень плавное переключение между текстом песни и релизами

### ISSUE THREAD

**Issue by OlyErofeeva** [sudo-mode/turbina#195]
Все анимации, которые сейчас сделаны через setTimeout и навешивание стилей, желательно в перспективе перевести на react-spring, он вроде постабильнее себя ведет.

**Comment by OlyErofeeva** [comment]
Сереж, пока просто так нас назначила, будем делать, как появится время. 
Тут приключение не на 20 минут)

**Comment by OctopussyO** [comment]
Исправлено #215
