### ISSUE TITLE
Счетчик времени по окончании трека превращается в тыкву (-1:0-1)

### ISSUE THREAD

**Issue by OlyErofeeva** [sudo-mode/turbina#203]
:boom: Для воспроизведения нужно обновлять страницу

**Comment by OctopussyO** [comment]
@OlyErofeeva Поясни, пожалуйста, что значит "обновлять страницу"? В какой момент? Дослушиваю до конца, у меня не выпадает это время.

**Comment by OctopussyO** [comment]
Исправлено #205
